google_analytics:

title: Your site title
description: Your site description

baseurl: "/odet_landing_page"
plugins:
  - jekyll-seo-tag

exclude: [
  package.json,
  package-lock.json,
  postcss.config.js,
  readme.md,
]

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
